// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCunSnhlgD6d6z30jBvRuU5ZvySCnvWl2Q',
    appId: '1:449275884989:web:41f7c185bc4b3311768ed4',
    messagingSenderId: '449275884989',
    projectId: 'ringfnder',
    authDomain: 'ringfnder.firebaseapp.com',
    storageBucket: 'ringfnder.firebasestorage.app',
    measurementId: 'G-39X802SKQ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzksYj12zSz7uc9IHZ6vJkdiKLylqUnAQ',
    appId: '1:449275884989:android:5087b8e7780a8cd5768ed4',
    messagingSenderId: '449275884989',
    projectId: 'ringfnder',
    storageBucket: 'ringfnder.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGdYw1tnatrEWAgjt2LgRZqsq5nSXNjQE',
    appId: '1:449275884989:ios:c683a53e8bced897768ed4',
    messagingSenderId: '449275884989',
    projectId: 'ringfnder',
    storageBucket: 'ringfnder.firebasestorage.app',
    iosClientId: '449275884989-3m82avehmq12f2daa5onr6qnf64p3lr8.apps.googleusercontent.com',
    iosBundleId: 'com.example.ringfinder1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGdYw1tnatrEWAgjt2LgRZqsq5nSXNjQE',
    appId: '1:449275884989:ios:c683a53e8bced897768ed4',
    messagingSenderId: '449275884989',
    projectId: 'ringfnder',
    storageBucket: 'ringfnder.firebasestorage.app',
    iosClientId: '449275884989-3m82avehmq12f2daa5onr6qnf64p3lr8.apps.googleusercontent.com',
    iosBundleId: 'com.example.ringfinder1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCunSnhlgD6d6z30jBvRuU5ZvySCnvWl2Q',
    appId: '1:449275884989:web:5d0ea1c39b5f4d43768ed4',
    messagingSenderId: '449275884989',
    projectId: 'ringfnder',
    authDomain: 'ringfnder.firebaseapp.com',
    storageBucket: 'ringfnder.firebasestorage.app',
    measurementId: 'G-T0YZDWR9TB',
  );
}
